### ISSUE TITLE
Fix sky and water rendering

### ISSUE THREAD

**Issue by eira-fransham** [eira-fransham/seismon#7]
# Motivation

At some point in the porting process, the sky started rendering like a normal brush and the water stopped moving.

# Proposal

Figure out what changed, and fix it. This should be a pretty easy fix, because most of the code related to sky and water is unchanged from Richter.

**Comment by soulwa** [comment]
hey! found this engine from your post on r/rust. I don't have a ton of experience with quake or bevy but I'm definitely interested in helping out with this project, and this one's marked "good first issue"- would it be alright if I tried to work out this issue? 

also, I played around with building `seismon` a bit and sky/water renders correctly on my Linux machine, but incorrectly on my Mac, so I think whatever changed is probably macOS specific. do you know if these textures were ever rendering correctly on mac? I'll be able to bisect this later today or tomorrow either way

**Comment by soulwa** [comment]
figured this out - it's actually largely just fixed by converting `lightmap_anim_frames` to the packed `Vector4` format, as suggested in a `TODO`. the issue is just that with OpenGL/Vulkan/WebGPU standards, floats in an array have to be aligned to 16 bytes, hence the use of `UniformArrayFloat`. Metal has no such requirement though, and so the uniform buffer on mac was just overwriting the `time` float with some lightmap value. In fact, every value in the `FrameUniforms` buffer was pretty much nonsense on mac, but `time` was the easiest to notice.

I've put together a PR which will fix this- it's pretty small/straightforward, but will save you the trouble. I've tested on Linux and Mac, and ordinary demo play/profiling seems to be good.

**Comment by eira-fransham** [comment]
Closed by #8
